ua-snap/data-api

.gitignore
Pipfile
Pipfile.lock
application.py

This PR enables the API to fetch the fire data for a given lat and lon.

Learning APIs by getting fire data

---

.gitignore
application.py
requirements.txt

Adds requirements.txt, provides the `application` object that EB expects, adds a bit of stuff to the `.gitignore`

Modifies code so the API can be deployed to Elastic Beanstalk

---

.gitignore
Pipfile
Pipfile.lock
application.py
config.py
routes/__init__.py
routes/fire.py
routes/iem.py
routes/permafrost.py
templates/iem.html
templates/permafrost.html
validate_latlon.py

This PR cleans up the API and closes out some minor issues where the API failed in instances where no data was available. We have also "minified" the key-value structure of the returned data to enhance brevity on the client-side.
This PR includes the IEM endpoints (see #12) and there is still a bit of common code that should be deduplicated (layer fetching and handling of errors and no data in particular), see #6. I think #6 can get addressed in a new branch and PR and should be sorted prior to developing too many new endpoints.
Closes #11 Closes #4 Closes #7 Closes #8

Tidy Up the API

---

README.md
fetch_data.py
luts.py
routes/fire.py
routes/permafrost.py

This PR pulls functions that can be used across multiple endpoints into a common `fetch_data.py` module. The module is responsible for making requests, generating WMS and WFS URLs for a given Geoserver Workspace, and then for generating Geoserver WMS/WFS queries for Data Layers within a Workspace. Some 'no data' QC is included as well. This PR should make adding new endpoints much faster as the endpoints will only need to package the response.
Closes #6

De-duplicate functions used across multiple endpoints.

---

routes/iem.py
templates/index.html

Grab-bag of minor tweaks related to the IEM endpoint.

IEM endpoint edits

---

routes/__init__.py
routes/huc.py
templates/huc/abstract.html
templates/huc/huc8.html
templates/index.html

These changes add an endpoint for a GeoJSON string of a HUC-8 polygon.

add HUC-8 polygon endpoint

---

application.py
routes/huc.py
static/style.css
templates/base.html
templates/fire/abstract.html
templates/fire/point.html
templates/forest/abstract.html
templates/forest/point.html
templates/geology/abstract.html
templates/geology/point.html
templates/glacier/abstract.html
templates/glacier/point.html
templates/huc/abstract.html
templates/huc/huc8.html
templates/iem/abstract.html
templates/iem/huc.html
templates/iem/point.html
templates/index.html
templates/permafrost/abstract.html
templates/permafrost/point.html
templates/physiography/abstract.html
templates/physiography/point.html

Go to each endpoint and ensure that it still works and I didn't break the demo queries.  Ensure that all pages are styled.

Update base templates for HTML, adds minimal styling via Bulma

---

routes/iem.py
templates/iem/huc.html
templates/iem/point.html

Test this on a couple of other (working) HUC endpoints please!  Check that the HTML looks OK for the point + HUC docs too.
Please squash merge this.

Csv for huc

---

data/csvs/ak_communities.csv
luts.py
routes/recache.py

Refactor to caching code to simplify the process of collecting valid endpoints. Fixes missed endpoints.
In the future, this code will pick up any new endpoints that have the keywords **/point/** or **/huc/** or **/protectedarea/**. If we ever need additional factors to search by, we will need to revisit this code to add those expected values from a generated JSON.

Refactors caching code for simplicity and accuracy

---

routes/recache.py
varnish-configuration/default.vcl

This PR makes it so that the caching process does not attempt to use the AK communities JSON in the /area as that is done via /point.

Recache fix

---

luts.py
routes/vectordata.py

This PR adds Alaskan Game Management Units and Canadian First Nations to available GeoJSONS which are now available at:  /places/all, /places/game_management_units, and /places/first_nations
Closes #90

Adds AK Game Management Units and Canadian First Nations

---

generate_requests.py
routes/alfresco.py
routes/taspr.py
templates/index.html
templates/mmm/abstract.html
templates/mmm/month.html

This PR adds the ability to generate min, mean, and max values from historical and projected scenarios. 
There are 5 expected outputs from this PR:
**Historical Min-Mean-Max**
- http://localhost:5000/mmm/jan/historical/65.0628/-146.1627
**Projected Min-Mean-Max** 
- http://localhost:5000/mmm/july/projected/65.0628/-146.1627
**Historical & Projected Min-Mean-Max**
- http://localhost:5000/mmm/jan/hp/65.0628/-146.1627
**JSON dump of all available min-mean-max data for a given point**
- http://localhost:5000/mmm/july/all/65.0628/-146.1627
**CSV download of all available min-mean-max data for a given point**
- http://localhost:5000/mmm/jan/65.0628/-146.1627?format=csv
Try several places and check that the CSV output looks good!

Arctic EDS January & July Min Mean Max Temperature Endpoint

---

routes/taspr.py

This PR combines the requests for the ArcticEDS client side into a single function to have the client able to request one endpoint and receive all of the data required.

Adds /eds/temperature and /eds/precipitation requests for consolidated ArcticEDS plate requests.

---

routes/taspr.py

Closes #205.
XREF https://github.com/ua-snap/arctic-eds/issues/65.
This rounds temperature values from the `/mmm/temperature` endpoint the same way they are rounded from the `/taspr` endpoint (1 decimal place).
To test, make sure the example URLs from this documentation page return 1 decimal place:
http://localhost:5000/mmm/temperature
And also make sure the example URLs on the `/mmm/precipitation` endpoint documentation page continue to be rounded to whole numbers:
http://localhost:5000/mmm/precipitation

Round temperature values from /mmm endpoint to 1 decimal place

---

README.md

Additions to the README specific to the /update/ endpoint.

---

routes/__init__.py
routes/beetles.py
templates/beetles/abstract.html
templates/beetles/area.html
templates/beetles/point.html
templates/index.html
templates/taspr/abstract.html
validate_data.py

This PR integrates the spruce beetle coverage for collection of the spruce beetle risk at a point or area in the state of Alaska. The returned values are 0 = no data, 1 = low risk, 2 = moderate risk, 3 = high risk and changed to text representation of the risk before passing it as JSON or CSV file. 
To run this branch, be sure to set your environment variable as such:
export API_RAS_BASE_URL=https://apollo.snap.uaf.edu/rasdaman

Spruce beetle coverage integration

---

routes/eds.py

This adds the elevation data to the JSON object returned for Arctic EDS point queries. 
XREF https://github.com/ua-snap/arctic-eds/issues/237

Adds elevation data to returned JSON object for Arctic EDS.

---

routes/beetles.py
templates/beetles/abstract.html
templates/beetles/area.html
templates/beetles/point.html
templates/index.html

This PR makes the changes required to match the beetle coverage data's meaning of climate protection from spruce beetles. This includes returning new fields in CSVs and the definitions being high climate protection, minimal climate protection, and no climate protection.
This PR is required for the changes to the NCR application for the beetle coverage portion of the report.

Beetle coverage changes to match climate protection meaning of data

---

fetch_data.py
routes/__init__.py
routes/indicators.py
validate_data.py

This is kind of a placeholder PR since we are planning to merge this branch with the quickness. We have tested the functionality of this branch through NCR via https://github.com/ua-snap/iem-webapp/pull/504, so I'm planning to do a quick code review before we merge this.

Add cordex indicators endpoint

---

templates/base.html

This PR adds the accessibility statement to the footer in the API for all templated pages.
Closes #245

Accessibility statement added to footer in API.

---

routes/seaice.py
validate_data.py

Adds a check for any sea ice concentration above 100% and provides an additional error code of 253 to the list of known no data values.
Closes #246

Sea Ice improvement

---

routes/degree_days.py

Adds community name to downloaded CSV file if community ID is provided in degree day end points.
To test this change, try the following two endpoints:
http://localhost:5000/mmm/degree_days/freezing_index/all/60.1043/-149.442?format=csv&community=AK354
http://localhost:5000/design_index/freezing/hp/60.1043/-149.442?format=csv&community=AK354
Closes #253

Adds community name to downloaded CSV file

---

application.py
static/robots.txt

Adds robots.txt file + new application route to access it from the static directory.
Closes #117

Adds robots.txt file

---

templates/taspr/abstract.html

This PR fixes the name error of the projected Precipitation dataset on this page: http://localhost:5000/taspr/
Closes #263

Fixes the naming error of the projected Precipitation dataset.

---

templates/index.html

This PR adds new introductory text to the data API home page that gives a bit of information about what an enduser may have stumbled upon and the power that they now have in their hands 😃 
Closes #32

New introductory text for landing page

---

csv_functions.py

This PR changes the URL that is supplied in all of the CSV metadata that used to point at the NCR. It instead points at the data endpoint from which the CSV was generated.
Fixes #355

Changes the metadata for all CSVs to point at the URL to get the data from the API.

---

README.md

This PR closes #348 .
Just check out `README.md` to see the changes, and feel free to suggest more!

update env variables and example permafrost query

---

static/style.css
templates/base.html

Closes #305 
Test by:
- Confirm that the language of the footer for AA/EO matches exactly `UA is an affirmative action/equal opportunity employer, educational institution and provider and prohibits illegal discrimination against any individual: http://www.alaska.edu/nondiscrimination` (we won't deviate from this anywhere)
- notice the slightly gentler colors for the background.

Updates footer, slight style changes

---

routes/eds.py

This PR simply changes the EDS endpoint for precipitation frequency to match the new endpoint.

Changes EDS endpoint for precipitation frequency to match new endpoint.

---

routes/taspr.py

This PR fixes the algorithm for generating the annual mean temperature summary where the min and max are taken from the yearly means rather than the maximum or minimum of the tasmax / tasmin respectively. 
These are giving values much closer to the expected annual values we saw in the previous iteration of the temperature summary for the ArcticEDS.
To test, you can run this branch and request:
http://localhost:5000/eds/temperature/64.8378/-147.716 
The above URL shows temperature data for Fairbanks.

Updates temperature summary with annual min, mean, and max

---

postprocessing.py
routes/eds.py
routes/hydrology.py

This PR adds the ArcticEDS endpoint for the hydrology section of the report. This code generates the min-mean-max for each of the months in a given era such as historical being 1950-2009 and then takes the the decadal annual means to find the min-mean-max from those values. 
The summary contains those values in each of the models / scenarios as "Annual" which the ArcticEDS populates its tables from. In addition, it contains the CSV preview, similar to other EDS endpoints in the API currently.
Be sure to set your environment to Apollo:
`export RAS_API_BASE_URL=https://apollo.snap.uaf.edu/rasdaman/`

Adds EDS endpoint for Hydrology data

---

routes/permafrost.py

This PR fixes the NCR permafrost endpoint by requesting a different data volume from Rasdaman than the ArcticEDS does. This will return 3 models and 2 scenarios for the /ncr permafrost endpoint now, while keeping the ArcticEDS endpoint the same as it was previously.
Closes #373

Fixes NCR permafrost endpoint by adding new conditional for grabbing required NCR data from Rasdaman.

---

routes/indicators.py

This PR resolves an unhandled 500 in the `indicators` route when a lat-lon was supplied that is inside the BBOX, but is "off the map" in the sense that there is no data available for that specific point. This is often triggered when a marine lat-lon is used because most of our data is terrestrial.
I added a second `except` block that seems to resolve the issue, cleaned up some un-used imports, an updated a docstring while I was in there.
Try the following routes and outcomes:
http://127.0.0.1:5000/indicators/base/point/foo/-143.24    should yield Bad Request
http://127.0.0.1:5000/indicators/base/point/65/-143.24     should yield valid data JSON
http://127.0.0.1:5000/indicators/base/point/45/-143.24.    should yield Invalid Coordinates …

fix no data handling

---

csv_functions.py
routes/taspr.py

This PR changes the precipitation frequency CSV to have exceedance probability rather than return interval. This simply checks if a CSV is being requested, and modifies the value that is being stored in that column.
Closes #382

Changes the precipitation frequency CSV to have exceedance probability.

---

routes/taspr.py

Removes commented out elif block.

---

templates/documentation/hydrology.html

Adds hydrology model outputs GN link in source data section

---

templates/index.html

Check the home page!  Links should work + text should not have errors.
Closes #390

Credit rasdaman + add license

---

luts.py
routes/recache.py

This PR updates the desired cached endpoints for the API.

Updates endpoints to be cached by the recache functions.

---

routes/indicators.py
templates/documentation/indicators.html
templates/index.html

This PR adds the indicator documentation to the API. 
Closes #269

Adds indicator documentation to API

---

luts.py

This PR reorganizes the LUT for the recaching function to first do all point locations for ArcticEDS, then all point locations for the NCR endpoints, and finally all area summaries for the NCR in our production cache.

Updates recaching order and adds missing endpoints for recaching.

---

routes/fire.py

This PR changes the name of the layer in Geoserver to match the correct layer going forward.

Updates WFS target to match correct layer name.

---

templates/documentation/beetles.html

This PR adds the Beetles documentation to the API under http://localhost:5000/beetles/
Closes #226

Adds Beetles documentation to the API

---

routes/seaice.py
templates/documentation/seaice.html
validate_data.py
validate_request.py

This PR adds the endpoint /seaice/enddate/ which looks at the ANSI datetime axis of the sea ice coverage to determine the most recent time slice of the data. It returns a JSON object of { "year": <max_year>, "month": <max_month> }
To test, simply go to:
http://localhost:5000/seaice/enddate/

Adds API endpoint for determining latest month and year for HSIA data.

---

templates/documentation/degree_days.html

Adds one sentence (highlighted below) to the degree day documentation template.
Closes #228

Make degree day units explicit

---

routes/taspr.py

remove unused function in `taspr`

---

luts.py
routes/beetles.py

This PR has a few small bug fixes to allow for the beetles endpoint to return data from both Apollo and Zeus, and to allow for the search functionality to work with the new all_areas shapefile. 
To test this PR, try going to the following URL endpoints:
Point your local API at Apollo first.
export API_RAS_BASE_URL="https://apollo.snap.uaf.edu/rasdaman/"
**Beetle Risk**
http://localhost:5000/beetles/point/65.4833/-155.634
**Search Functionality**
http://localhost:5000/places/search/64.57/-149.17?tags=ncr
export API_RAS_BASE_URL="https://zeus.snap.uaf.edu/rasdaman/"
Try those same URLs again and you should expect them both to return with the same data now. 
To see them in their broken state, do the following:
git checkout main
export …

Bug fixes for expected NCR functionality
