ua-snap/data-api

- .platform/nginx/conf.d/redirects.conf
Related to #21.
Yesterday, I moved the data-api Elastic Beanstalk instance behind a CloudFront distribution to set up HTTPS, and changed Route 53 to point to the CloudFront distribution instead of directly to the Elastic Beanstalk instance. So, the server infrastructure changed from this:
Route 53 → Elastic Beanstalk
To this:
Route 53 → CloudFront → Elastic Beanstalk
Almost everything is working as intended, but whenever there is a case where the data-api Flask application needs to perform a redirect, it is redirecting to the Elastic Beanstalk domain (testing.eba-hkca5w5b.us-west-2.elasticbeanstalk.com instead of the custom (eathmaps.io) domain.
Currently the Flask application is set to force routes to have a trailing slash. So, for example, this URL loads just fine and retains the custom …
> Redirect Flask redirects back to custom domain.

- config.py
This PR is a slight modification of the bounding box used to validate queries and should prevent queries for Attu, Shemya, Eareckson, etc. from throwing out-of-bounds errors.
Closes #75
> expand eastern bounding box

- routes/permafrost.py
- validate_data.py
Closes #88.
This PR allows us to partially prune data responses. Without this PR, we are using the `prune_nodata` function to detect when a response object is missing data entirely (in which case we return a 404). But if the response object is a hybrid of data & nodata, as is common with permafrost queries, we respond with a hybrid object where the nodata fields are set to `null`. However, this approach has the problem of returning responses like this, where the GIPL data is `nulled`ed out while retaining a deeply nested structure:
https://earthmaps.io/permafrost/point/64.5011/-165.406
This creates needless complexity for the web app code to decipher.
This PR allows us to partially prune the data response object to a specified prune depth, so we get this:
```
{
"gipl": null,
"jorg": { …
```
> Support partial nodata pruning and remove deeply nested nulls from permafrost output

- fetch_data.py
- routes/boundary.py
- templates/boundary/huc.html
- templates/boundary/huc/abstract.html
- templates/boundary/huc/huc8.html
This PR makes a small change to fix an error with the `elevation/huc` endpoint that was caused by failure to account for a new format returned through a WCS request: GeoTIFF!
To test, try some of the following endpoints that return an internal server error on the live API:
[http://localhost:5000/elevation/huc/19010208](http://localhost:5000/elevation/huc/19010208)
[http://localhost:5000/elevation/huc/19070506](http://localhost:5000/elevation/huc/19070506)
[http://localhost:5000/elevation/protectedarea/NPS7](http://localhost:5000/elevation/protectedarea/NPS7)
[http://localhost:5000/elevation/protectedarea/NPS5](http://localhost:5000/elevation/protectedarea/NPS5)
This PR also makes a change to remove the HUC class fragment from the HUC boundary endpoint, e.g. the `/huc8/` in …
> Fix HUC DEM errors and remove HUC class fragment from HUC endpoint

- .platform/nginx/conf.d/timeouts.conf
This allows for the Nginx configuration that hosts the API to have a timeout of 300 seconds to allow for many 502 / 504 errors to be eliminated. Without this configuration change, we get a lot of timeouts (502s / 504s) when querying larger protected areas and HUCs.
> Increases the Elastic Beanstalk timeout to 300 seconds

- routes/alfresco.py
Closes #130.
Point queries return decadal and 30-year era ALFRESCO data using JSON keys with dashes (e.g., "2040-2069"). Polygonal queries currently return decadal data with dashes and era data with underscores (e.g., "2040_2069"). This updates the polygonal queries to use dashes to be consistent with the other keys from the ALFRESCO endpoint.
> Use dashes instead of underscores for ALFRESCO polygonal era keys

- routes/permafrost.py
- validate_data.py
Closes #120.
This PR changes the way that our response pruning algorithm works. In the current main branch, the pruning function allows us to set the minimum pruning depth so that certain keys are preserved even if they have a null value. Keeping certain keys intact makes it easier to handle the data on the client-side without inspecting the structure of the entire JSON object.
For example, we want the "gipl" key (and "jorg" and "obupfx" keys) to be preserved in the following response even though they have null values:
https://earthmaps.io/permafrost/point/52.9025/172.909444
The downside to this approach is that the pruning algorithm is too aggressive at higher nesting depths. For example, we want the "alt" key to be preserved in this response even though the alt values are null: …
> Preserve keys for null values if any sibling contains data in pruned response

- routes/elevation.py
- validate_data.py
Closes #125.
This PR is dependent on #133, so I'm setting this PR as a draft until #133 is merged.
To test, compare this URL between production and the `elevation_nodata` branch running locally:
https://earthmaps.io/elevation/point/68.55/-174.88
http://localhost:5000/elevation/point/68.55/-174.88
Instead of this:
```
{
"max": -9999,
"mean": -9999,
"min": -9999,
"res": "1 kilometer",
"title": "ASTER Global Digital Elevation Model",
"units": "meters difference from sea level"
}
```
You should see this:
```
{
"max": null,
"mean": null,
"min": null,
"res": "1 kilometer",
"title": "ASTER Global Digital Elevation Model",
"units": "meters difference from sea level"
}
```
> Convert elevation nodata to null in JSON response

- fetch_data.py
- routes/alfresco.py
- templates/alfresco/abstract.html
- templates/alfresco/area.html
- templates/alfresco/local.html
- templates/alfresco/point.html
- validate_data.py
To test, use the new `veg_type` endpoint for any lat/lon or area query that works for the existing ALFRESCO endpoints (`flammability` and `veg_change`):
http://localhost:5000/alfresco/veg_type/
This new endpoint can use some better documentation and example output. This has been captured in #154.
> Add new vegetation type (aka veg_type) endpoint that returns each vegetation type as a percentage

- fetch_data.py
- routes/alfresco.py
- templates/alfresco/abstract.html
- templates/alfresco/area.html
- templates/alfresco/local.html
- templates/alfresco/point.html
Closes #153.
Closes #154.
Closes #160.
Closes #162.
This PR does several things:
- Fixes all area endpoints, which broke mysteriously. After the recent Rasdaman upgrade on Zeus (and earlier on Apollo), the shape of polygon masks suddenly did not match the shape of the original data arrays. To solve this, we are now cropping polygon masks to the correct shape.
- Switches to using the new `alfresco_relative_flammability_30yr` Rasdaman coverage that has pre-computed 30-year projected eras + two distinct historical eras (1950-1979, 1980-2008).
- Removes code that handled dynamic aggregation of ALFRESCO data into 30-year eras since this work has now been precomputed before the Rasdaman ingest.
- Removes the old `veg_change` (vegetation transitions) endpoint that has been superseded by the new …
> Use new flammability coverage with precomputed eras, streamline ALFRESCO output, and fix polygon mask shape mismatches

- fetch_data.py
Closes https://github.com/ua-snap/iem-webapp/issues/337.
The comparison operation used to determine if nodata values are sneaking through the polygon mask is failing to catch nodata values that are close, but not precisely the same, as the value we are checking against (-9.223372e+18). It appears that the -9.223372e+18 values become slightly different when they are averaged across decades. This was causing ~-9.223372e+18 values to sneak through the polygon mask only for 30-year era summaries of taspr data.
For example, look at the 30-year summary data (not the decadal data) for this endpoint:
http://localhost:5000/taspr/area/NPS12
Without this PR, the ~-9.223372e+18 values sneaking through the polygon mask are being included in the average of the 30-year area summary data, making the …
> Catch and convert remaining taspr nodata values that sneak through polygon mask

- routes/vectordata.py
Looks like this problem started occurring when the Aleutian Island HUCs were removed in https://github.com/ua-snap/geospatial-vector-veracity/pull/86.
To replicate, view a point query from a Western Aleutian Island while running the data-api from the `main` branch. For example:
http://localhost:5000/places/search/51.77/-176.67
The `no_huc_fix` branch will return a valid response, which I have tested against the web app.
Xref: https://github.com/ua-snap/iem-webapp/issues/317.
> Fix server error and return valid response if point query returns no nearby HUCs

- fetch_data.py
- routes/elevation.py
This PR fixes the summary elevation values that are returned by the API (and used by the dynamic text in the CIR tool, [see this issue.](https://github.com/ua-snap/iem-webapp/issues/317) This fix is accomplished by passing the GeoTIFF source nodata values to the zonal stats function. Previously, the zonal stats used a `nodata=np.nan` implementation which (now obviously) will not work when the no data value is -9999 and not `np.nan`. To test this out visit http://localhost:5000/elevation/area/NC12 on the current main branch of the API. You'll fetch extreme values that really do not make any sense!!
Visit the same URL on this branch and the results are 
```
{
"max": 2857.0, 
"mean": 21, 
"min": -42.0, 
"res": "1 kilometer", 
"title": "ASTER Global Digital Elevation Model Zonal Statistics", …
```
> Fix Elevation Stats to Ignore NODATA

- routes/vectordata.py
This PR will include both CA First Nations and AK Game Management Units (GMUs) in the results of the `search` endpoint. To test this PR, visit http://localhost:5000/places/search/64.9/-140.8 and verify that the `"Tr'ondëk Hwëch'in"` is included in the `ca_first_nations_near` portion of the results. Also verify that GMU 20E and GMU 25B are in the `game_management_units_near` item. 
This is a pretty quick end-of-the-day PR so please try a few other queries and check the two new dicts I've mentioned here.
> Add AK GMUs and CA First Nations to Search Endpoint

- routes/taspr.py
- templates/mmm/precipitation.html
- templates/mmm/temperature.html
- validate_request.py
This PR adds an optional start year and end year to the endpoint for generating the min, mean, and max for historical, projected, or both in the Jan and July temperature and annual precipitation totals coverages. 
Ensure that you try doing something like this:
**Without date range:**
http://localhost:5000/mmm/temperature/jan/hp/65.0628/-146.1627
**With date range:**
http://localhost:5000/mmm/temperature/jan/hp/65.0628/-146.1627/1901/2020
You should see that for that particular set of queries that the historical records do not change as it has the full range of data to find min, mean, and max but a different set of values for the projected values since we are only looking for data between 2006 - 2020.
> Adds new variables to temperature and precipitation MMM endpoints

- generate_requests.py
- routes/taspr.py
- templates/mmm/abstract.html
- templates/mmm/precipitation.html
- templates/mmm/temperature.html
This PR adds a new endpoint for generating the min-mean-max for mean annual temperature data coming from the annual_mean_temp coverage.
This builds on the recent /mmm endpoint, allowing the option for temperature to be queried without specifying one of the month variable options (jan / july), instead returning min-mean-max of mean annual temperature for the specific time period, or the non-summarized mean annual temp values if the "all" value is used for the time period variable. This is done in a similar way to the /mmm/precipitation, simply omit the month value:
[http://localhost:5000/mmm/temperature/historical/65.0628/-146.1627](http://localhost:5000/mmm/temperature/historical/65.0628/-146.1627)
The recently added functionality for specifying the start and end years to summarize over …
> Add arctic eds mean annual temp to mmm

- fetch_data.py
- routes/__init__.py
- routes/snow.py
- templates/index.html
- templates/mmm/abstract.html
- templates/mmm/snow.html
- validate_data.py
This PR creates a new endpoint under the top-level `mmm` route to access modeled snowfall equivalent data (SFE) for ultimate use in the Arctic-EDS. The routing follows the existing convention for summarizing over either `historical` or `projected` or both (`hp`) - or for accessing `all` data values. The `all` option is also available for CSV export. The native temporal resolution of this dataset is decadal, so custom time-slicing is *not* available in this endpoint because users could unwittingly summarize over very few values. For example, a 2020-2050 summary would only compute min-mean-max over 3 values - not 30.
To use this endpoint fire up the API and point it at Apollo
`export API_RAS_BASE_URL=http://apollo.snap.uaf.edu:8080/rasdaman/`
Some URLs to test: …
> Adds a mmm snow endpoint to access historical and modeled snowfall equivalent.

- fetch_data.py
- routes/alfresco.py
- routes/degree_days.py
This PR provides a more general handling of missing Rasdaman coverages. The motivation for this PR was to prevent changes within and between the various Rasdaman servers (Zeus, Apollo) from blocking development on the API. In this PR an exception provides a specific warning message if the DescribeCoverage request to Rasdaman fails.
To test this behavior:
- Point the API to Apollo
- `export API_RAS_BASE_URL=http://apollo.snap.uaf.edu:8080/rasdaman/`
- Edit Line 34 on `alfresco.py` such that coverage name for relative flammability is incorrect and doesn't match what is on Apollo, e.g., change `alfresco_relative_flammability_30yr` to `FOOalfresco_relative_flammability_30yr`
- Run the API
- Confirm that you observe a terminal error message, it should read: "Warning: Coverage …
> Handle missing Rasdaman coverages

- routes/degree_days.py
- routes/taspr.py
- templates/design_index/point.html
Closes #197.
This PR updates the `/design_index` endpoints to support the same options as the `/mmm` endpoints:
- historical
- projected
- hp
- all
The projected data from the `projected` and `hp` options is the mean of the data across the two available models.
With this change, when you click a point on the map of the Design Thawing Index or Design Freezing Index plate in the Arctic EDS web app, you are shown a data table similar to what you see in the Temperature and Precipitation plates (means, not data for individual models).
The data that had previously been returned by the `design_index` endpoints is still accessible via the `all` option.
To test, view the revised Design Index endpoint documentation here and make sure the URLs work as expected: …
> Summarize Design Thawing/Freezing Index data across models, but continue to provide all data through "all" endpoint

- routes/snow.py
- templates/mmm/abstract.html
- templates/mmm/snow.html
This endpoint is being updated to return SI units with appropriate levels of precision. In this case, this means changing inches to millimeters with no decimal places.
To test this endpoint visit http://localhost:5000/mmm/snow/snowfallequivalent/hp/61.5/-147 and confirm that the results are as follows:
```
{
"historical": {
"sfemax": 4876, 
"sfemean": 3701, 
"sfemin": 2946
}, 
"projected": {
"sfemax": 3945, 
"sfemean": 3419, 
"sfemin": 2589
}
}
```
You may also try a few other locations - all returned values should have no decimal places.
XREF these issues:
https://github.com/ua-snap/rasdaman-ingest/issues/35
https://github.com/ua-snap/rasdaman-ingest/issues/34
Note - the "Prettier" formatter on VSCode did a lot of formatting to the HTML that documents this endpoint.
> Modify snow endpoint to use mm units with no decimal places.

- routes/taspr.py
- templates/mmm/abstract.html
- templates/mmm/precipitation.html
This is a minor update to the API that modifies the precipitation values returned by `mmm` routes such that they provide precipitation values in millimeters with no decimal places.
To test this endpoint visit http://localhost:5000/mmm/precipitation/hp/65.0628/-146.1627 and confirm that the results are as follows:
```
{
"historical": {
"prmax": 578, 
"prmean": 356, 
"prmin": 231
}, 
"projected": {
"prmax": 823, 
"prmean": 447, 
"prmin": 257
}
}
```
You may also try a few other locations - all returned values should have no decimal places.
XREF these issues:
https://github.com/ua-snap/rasdaman-ingest/issues/37
https://github.com/ua-snap/rasdaman-ingest/issues/34
> Return precipitation for Arctic-EDS in mm with no decimals, not inches.

- routes/degree_days.py
- routes/permafrost.py
- templates/mmm/degree_days.html
- templates/permafrost/point.html
Closes #202.
To test:
- Try out some example URLs from the [Design Index](http://localhost:5000/design_index/point) and [Degree Days](http://localhost:5000/mmm/degree_days/) endpoints (+ try some lat/lon coordinates of your own). Every value returned from these endpoints should be rounded to a whole number.
- Try the [Permafrost](http://localhost:5000/permafrost/point/) endpoint with several different lat/lon coordinates. Make sure all MAGT values are rounded to one decimal place.
- Observe that values in the example output in the documentation pages linked above match the expected decimal precision.
> Round degree days to whole numbers, and MAGT to one decimal

- luts.py
- routes/vectordata.py
- templates/boundary/abstract.html
This PR adds 10 census area and 19 borough polygons (see map below) to the API and makes them available for queries, GeoJSON fetching, and the nearby polygon "geo-search" functionality.
I recommend trying the following areas in various queries, because these were the intially troubling polygons due to either extent or size:
`BORO1`: The Aleutians Borough
`BORO3`: The North Slope Borough
`CENS6`: Nome Census Area
`CENS9`: Bethel Census Area
I've tested these for the Elevation, Relative Flammability, and Temperature area summary queries. Note that some of these queries will take several minutes when not cached. Also note that when you initially launch the API it will take a moment to download the shapefiles and generate the appropriate JSONs.
To see the full list of new polygons added, …
> Add AK borough and census areas polygons for zonal area queries

- fetch_data.py
- routes/__init__.py
- routes/landfastice.py
- templates/index.html
- templates/landfastice/abstract.html
- templates/landfastice/point.html
- validate_data.py
This PR adds the first version of the landfast sea ice endpoint.
The data accessed by this endpoint are described in this [curation notebook](https://github.com/ua-snap/ardac-curation/blob/main/seaice/pipeline/qc.ipynb) and have been through a [QC process](https://github.com/ua-snap/ardac-curation/blob/main/seaice/pipeline/qc.ipynb). The data rely on the coverage `landfast_sea_ice_extent` which is currently on Apollo, but not Zeus.
We expect this service endpoint to significantly grow in both query versatility and in availability of diffferent data variables - but this initial service only provides a time series of landfast ice status (present or absent) for a geographic point. A value of `1` indicates that landfast ice exists. A value of `0` indicates that landfast ice does not exist.
To …
> Landfast Sea Ice Endpoint 1.0

- fetch_data.py
- routes/__init__.py
- routes/eds.py
This PR adds the new endpoint /eds/all/<lat>/<lon> to the API. This combines all of the report sections in the Arctic EDS web application and generates a long JSON listing of the returned data.
Each report section has a key indicating its underlying data such as "thawing_index" or "precipitation". 
Try a few valid lat / lon coordinates such as: 
http://localhost:5000/eds/all/68.0764/-153.5501
http://localhost:5000/eds/all/62.0764/-143.5501
Try some invalid lat / lon coordinates to see what is returned as well, such as:
http://localhost:5000/eds/all/22.0764/-123.5501
http://localhost:5000/eds/all/52.0764/-123.5501
> New endpoint for generating combined JSON for all Arctic EDS report sections

- routes/__init__.py
- routes/eds.py
- routes/wet_days_per_year.py
- templates/index.html
- templates/wet_days_per_year/abstract.html
- templates/wet_days_per_year/point.html
- validate_data.py
This PR adds an endpoint for the number of wet days per year (days where total precip accumulation is >= 1.0 mm).
The endpoints in this PR are min-mean-max summarized (except for `/all/`) but `wet_days_per_year` is a top-level route.
To test this PR, try a few different queries after setting your Rasdaman backend to Apollo.
http://localhost:5000/wet_days_per_year/projected/point/62.0628/-150
http://localhost:5000/wet_days_per_year/historical/point/68/-149
http://localhost:5000/wet_days_per_year/hp/point/62/-166.1627
http://localhost:5000/wet_days_per_year/all/point/69/-151
http://localhost:5000/wet_days_per_year/projected/point/65/-145/2070/2099
http://localhost:5000/eds/wet_days_per_year/point/65/-147
> Add wet_days_per_year endpoint

- routes/degree_days.py
- templates/mmm/degree_days.html
The new minimum and maximum years for historical ERA-Interim-based degree day endpoints was changed to be 1980 and 2009 on Apollo. This is a small change to restore the functionality of affected endpoints in the development API.
> Fix historical degree day min and max years

- fetch_data.py
- generate_requests.py
- routes/landfastice.py
- routes/permafrost.py
- templates/permafrost/point.html
- validate_data.py
This PR adds service endpoints for the most recent of GIPL model outputs (ten variables at 1 km spatial resolution) that were provided to SNAP by Sergey Marchenko in August 2022. The backend data supporting these endpoints is a Rasdaman coverage called `crrel_gipl_outputs` (currently on Apollo only) that was created by ingesting 6000 GeoTIFFs. The spatial extent of these data are Alaska only - although the Western Aleutian chain is not present. 
There are 3 model cases (5-Model-Average, GFDL-CM3, and NCAR-CCSM4), and two scenarios (RCPs 4.5 and 8.5).
Only point queries are implemented at this time.
To test this PR, try queries constructed as follows to fetch the complete set of GIPL model outputs (all models, scenarios, and years) for a point location: …
> Add service endpoints for the most recent GIPL 2.0 outputs

- README.md
- application.py
- generate_urls.py
- luts.py
- routes/alfresco.py
- routes/recache.py
- routes/vectordata.py
- validate_data.py
- validate_request.py
This PR changes the last of the remnants of our old process for downloading shapefiles locally and opening them via GeoPandas for analysis. This points the calls for the old HUC12 GDF to Geoserver WFS responses that are then loaded into a temporary GDF for analysis. In some cases, we are letting Geoserver do all of the work that was originally required such as finding the nearest HUC12 that intersects with a given lat / lon for the ALFRESCO local requests. 
Let me know if you have any questions, and please let me know if you spy anything that isn't right and should be changed.
Things to check:
- Ensure the ALFRESCO code works for any of the local endpoints for flammability and veg_change
- Ensure you don't see any outstanding areas where the GDFs are called from luts.py
- Any code that …
> Integrates HUC12 boundary calls and ALFRESCO local requests to Geoserver

- routes/beetles.py
This PR simply removes the trailing forward slash of the beetle's point query that was causing issues with our NCR application due to the need to redirect from the requested URL without a trailing slash to the expected API URL with a trailing slash. Without the trailing slash, the correct URL is requested for point locations, and the CORS works without having to redirect. 
To test, ensure that you can access this community in Chrome, Firefox, and Safari through the NCR application: http://dev.northernclimatereports.org/report/community/AK300
This branch has already been uploaded to the development API at: http://development.earthmaps.io
> Removes trailing forward slash at the end of beetle point location URL.

- fetch_data.py
- routes/permafrost.py
- templates/permafrost/point.html
This PR builds off of the `gipl_ncr_request` branch and:
- Drops some commits in the git history that had attempted to incorporate a historical baseline into the GIPL responses, before it was decided that this was an apples-to-oranges comparison. This PR includes only projected data in GIPL responses.
- Adds CSV and community ID support to the `/ncr/permafrost` endpoint, so URLs like this work as expected: http://localhost:5000/ncr/permafrost/point/64.8378/-147.716?format=csv&community=AK124 This means we now have era-summary CSV download buttons in the NCR app (in the `gipl_updates` branch) that matches the data displayed in the permafrost charts, consistent with the CSV download buttons in other sections of the app.
- Adds more error handling to pick up HTTP status codes from the …
> Remove historical data from gipl_ncr_request branch, add aggregate CSV support to GIPL era queries, etc.

- routes/permafrost.py
Closes #148.
Closes #150.
This PR replaces a couple problematic UTF-8 characters (`–` and `°`) in permafrost CSV metadata with unproblematic characters/strings.
To test, download a permafrost CSV. For example:
http://127.0.0.1:5000/permafrost/point/65.0628/-146.1627?format=csv
And try opening it with Excel to confirm that the binary gibberish is gone from the date ranges in these two lines:
```
```
And that all `°` characters have been replaced with the string `deg `.
> Replace UTF-8 characters in CSV metadata that Excel struggles with

- routes/taspr.py
This PR adds the ability to see the month selected in the file name when that month was included as part of the API endpoint URL.
Example: http://localhost:5000/mmm/temperature/july/all/60.1043/-149.442?community=AK354&format=csv
Try a few locations, some that are lat / lon coordinates and some that are communities.
Closes #252
> Updates CSV filename based on month if provided in URL.

- routes/degree_days.py
- templates/422/invalid_year.html
If min and max years are given for /mmm/degree_days endpoint, it will give a 422 error and use the invalid_year template.
To test this PR, try this endpoint:
http://localhost:5000/mmm/degree_days/freezing/hp/60/-156/1800/2099
Closes #191
> Uses invalid_year template for degree_days /mmm route

- application.py
- fetch_data.py
This PR adds the cache-control headers to our site which can inform upstream caches of how long we would like to cache a file for future reference. When pointed at the Varnish cache for either Rasdaman (maps.earthmaps.io) or the data API (earthmaps.io), it is specifying a max age of 90 days and matches the length of cached time on the Varnish servers.
To test this, you can go to the updated development.earthmaps.io site and look at the returned headers for max age in the cache-control section of the response header: http://development.earthmaps.io/alfresco/veg_type/area/19080309
Closes #73
> Adds cache control header fields to keep returned data for 90 days

- templates/documentation/taspr.html
Xref: #291.
This PR restores the "Projected maximum precipitation events" documentation that got lost during merge conflict resolution in #291.
> Restore maximum precipitation documentation that got clobbered in conflict resolution

- routes/recache.py
Closes #99.
This PR changes the `log_error` function in `routes/recachep.py` to write recache errors as warnings via the logging module, which writes its output to STDERR. I figure STDERR is a more appropriate target than STDOUT, and the logging module defaults to STDERR as well.
Also, I think writing these types of errors as `warning`s (not `info` and not true `errors`) is appropriate since they are worth noting but not show-stopping. Please let me know if you disagree!
To test, run the API and visit the recache URL from your browser (e.g., http://localhost:5000/recache/true). After 10-20 minutes, you should see some recache warnings show up in the terminal via STDERR .
> Use Flask logger to write cache errors to STDERR instead of local file

- validate_data.py
- validate_request.py
Closes #82.
For this PR, I looked into using third-party validation modules for input validation. I looked into Pydantic and Cerberus specifically. I discovered that these third-party modules are designed to perform validation on complex objects like dicts or classes, not simple strings, and offer nothing for simple string validation that is not already built in to Python.
I also realized after reading these documents that Python provides some simple methods to help with string validation that we can use instead of regular expressions, and went ahead and made these changes to simplify the code.
To test:
- Make sure that HUC-12 queries (and/or ALFRESCO point queries that query HUC-12s behind the scenes) and custom SNAP polygon queries (e..g, `FIRE2`, `BORO3`, `CENS4`) still work as …
> Simplify input validation

- fetch_data.py
Closes #260.
This PR simplifies the XML parsing in the `parse_meta_xml_str` function, as suggested in issue #260. I'm setting this PR as a draft for now until #306 is merged since this branch is based off the `lxml_coverage_parse` branch.
> Simplify XML parsing in parse_meta_xml_str function

- csv_functions.py
- luts.py
- routes/permafrost.py
- templates/documentation/permafrost.html
This PR closes #297 by removing all references to the old 4km GIPL data. 
The `run_point_fetch_all_permafrost` function called by the `@routes.route("/permafrost/point/<lat>/<lon>")` endpoint now packages the new 1km GIPL data instead (see line 256 in `permafrost.py`).
To test, run the `flask` application as described in `README.md`, and try:
[http://127.0.0.1:5001/permafrost/point/64/-145](http://127.0.0.1:5001/permafrost/point/64/-145)
Try out some other coordinates to make sure you are seeing data (or errors) as expected. You should see the first point data package titled "gipl_1km" instead of "gipl", which indicates the return from the `package_gipl1km_point_data` function at line 263 in `permafrost.py`. 
**Note:** The default endpoint link from the permafrost template …
> del 4km GIPL; del unused luts/imports

- routes/permafrost.py
- templates/documentation/permafrost.html
This PR:
- removes the `<summarize>` endpoint in `permafrost.py` and replaces it with a request argument `?summarize=mmm`. The `summarize` argument is left unchanged in the `fetch_gipl…()`, `run_fetch_gipl…()` functions, so the `run_ncr_requests()` function should work as usual.
- Adds explicit validation of any `?summarize=` and `?format=` args. Previously, bad arguments would default to None which continued to produce data (eg, `?summarize=mean` would still produce a non-summarized JSON result, which was confusing). This addresses issue #337 but only for the `permafrost.py` route. Explicit validation like this, if repeated in every `route/*.py` module, could become very redundant and could perhaps be moved to its own module specifically for validating request arguments (see issue #339). …
> Revise permafrost mmm

- csv_functions.py
- routes/permafrost.py
- templates/documentation/permafrost.html
This PR updates the logic in the WCPS request that generates the `mmm` summaries of the GIPL model output. The prior behavior was such that the only axis of the hypercube being summarized was time, and a summary was created for each climate future. Now time, model, and scenario are all summarized yielding a single `mmm` summary returned by the request. This also dramatically cuts down the overall number of WCPS requests required (from something like 18 to 3).
To test this PR visit the following routes and observe that all ten variables are summarized three times, one per summary statistic (min, mean, max):
Full time series (this route will summarize the entire time series because the summary arg is passed, but no year range is provided). Observe some compelling deltas between the min and …
> Permafrost WCPS Update

- csv_functions.py
- routes/taspr.py
- templates/documentation/taspr.html
Closes #335.
This PR changes the route for the proj_precip endpoint and updates the documentation and CSV metadata according to the checklist in #335.
To test, make sure all of the changes listed in #335 have been made.
> Rename and change route for proj_precip and update documentation

- templates/documentation/boundary.html
Closes #295.
This PR adds a note to the "Physical and Administrative Boundary Polygons" documentation page mentioning that endpoints that return a list of available places can also be downloaded as CSV files via the `?format=csv` parameter.
CSV output is not supported for endpoints that return GeoJSON polygon data (and for good reason!). So, I've also separated the "list of places" endpoints from the "GeoJSON polygon data" endpoints, documented them in separate tables, and also filled in both tables with missing endpoints.
To test, make sure all of the endpoints listed on the "Physical and Administrative Boundary Polygons" page work as expected, and all of the "Available places" endpoints return valid CSV data when `?format=csv` is added to the URL.
> Separate boundary documentation into two tables and add applicable CSV note

- templates/documentation/taspr.html
Closes #353.
This PR simply changes the names of the January and July temperature endpoints in the documentation to remove "min/mean/max".
After looking at this closer, this wasn't actually a mistake, but just poor wording. The January and July temperature endpoints do indeed return min, mean, and max data (even when not provided the `?summarize=mmm` parameter), but the "min/mean/max" in the endpoint names makes the rest of the documentation very confusing, so I've gone ahead and renamed them to:
- January temperature
- July temperature
- January temperature within year range
- July temperature within year range
... and also updated the corresponding output documentation to reflect this.
> Remove "min/mean/max" from January/July endpoint names

- csv_functions.py
- postprocessing.py
- routes/__init__.py
- routes/hydrology.py
- templates/documentation/hydrology.html
- templates/index.html
This PR adds the basic `/hydrology/point/<lat>/<lon>` endpoint, which includes a point data query with optional `?format=csv` and `?summarize=mmm` arguments. 
(You will notice that I did not use a WCPS request to get the min, mean, max values - instead I just summarized these from the regular WCS results. I could not seem to write a WCPS query that would return the correct data in this structure without resorting to a bunch of iteration wrapping the WCPS query, sending lots of round trip requests to rasdaman. This method seemed much simpler / more transparent to me, but of course I am open to suggestions!)
To test, run the flask application as described in `README.md`, then review the documentation at `/hydrology.html`. Then try:
Standard endpoint:
```
/hydrology/point/62/-145
``` …
> Add hydrology endpoint

- routes/hydrology.py
This PR adds the seasonal totals for the hydrology data to display in the hydrology section of the NCR. 
You get these additional seasonal totals when requesting /eds/hydrology currently, which in a future version of the API we could change if desired. 
In the returned JSON, for each variable and scenario, you should see a seasonal total for Spring, Summer, Fall, and Winter.
> Adds seasonal totals for the NCR of the hydrology data

- csv_functions.py
Closes #342.
This PR replaces the last remaining `°` characters in CSV exports with our de facto standard of writing, for example, `(deg F)`. I also scanned through our `csv_functions.py` file for other special characters and found no others to fix.
So, this should make our CSV exports fairly bulletproof against Excel UTF-8 weirdness except for a handful of alternative (Indigenous) place names with special characters. I've explained in #342 why there's not necessarily a good path forward to solve this, however.
> Remove UTF-8 characters from CSV metadata

- csv_functions.py
- routes/indicators.py
Closes #378.
This PR adds CSV export support for point and area indicators endpoints.
This required more changes than I anticipated because the indicators JSON output had some unnecessary era/model/scenario combinations (e.g., `historical` era with scenario `rcp45`) that always contained nodata and that, after being processed with our `nullify_and_prune` function, ended up as partial branches with null values (which is what `nullify_and_prune` is designed to do). This doesn't cause any problems on the webapp side, but because the functions we use to construct CSV rows expect a consistent level of key/value nesting, the functions didn't know what to do with the partial JSON branches.
To solve this, I've implemented some pruning of the JSON data in the `indicators.py` route before the data …
> Add CSV export to indicators endpoints

- csv_functions.py
Testing:
- Trigger a CSV download for an Indicators endpoint, such as: `localhost:5000//indicators/base/point/64.8378/-147.716?format=csv&community=AK124`
Check that there's no goofy special characters in the metadata header at the top.
> Remove extended-charset mm glyph

- static/style.css
- templates/422/invalid_latlon.html
- templates/base.html
This PR adds a simple Leaflet map to the API's 422 HTTP code returns when an invalid latitude / longitude has been requested. The map has the bounding box that is described in the returned page to more quickly highlight where our data boundaries are for our point based queries.
An example of this error can be found at: http://localhost:5000/temperature/point/80.0628/-146.162
Note: The color of the bounding box may need to be adjusted to be more visible, but let me know if you think that is the case.
Closes #420
> Adds map to API 422 returns for invalid latitude / longitude requests and shows the described bounding box on the map.

- routes/degree_days.py
- templates/documentation/degree_days.html
This PR is motivated by Arctic-EDS feedback that "historical" in the context of "historical modeled data" was causing the audience (engineers) to stub their toes. Generally this audience is less familiar with climate model data and they interpreted the "historical" label as "historical data must match observed station data."  
We're using the phrase "modeled baseline" instead.
To test this PR, make sure your API is pointing toward Zeus.
Then try some of the routes [listed here](https://github.com/ua-snap/data-api/pull/428) and verify that keys and labels all read "modeled baseline". This key is often nested under "daymet".
Also review the documentation template to verify that the references to "historical" data are also updated: http://localhost:5000/degree_days/
This PR also removes some …
> Degree days: replace all instances of "historical" with "modeled baseline"

- csv_functions.py
Closes #432.
This PR fixes the issue described in issue #432. To test, try each of the URLs in #432 and make sure the bad `scenarios` column has been removed from the CSVs. You may need to use a different browser or a private window to see the difference if you have visited the same URLs recently. Chrome caches CSV downloads very aggressively! Not sure about other browsers.
Also, spot check some non-mmm degree days CSV URLs to make sure this change didn't impact those. They look good to me, though.
> Remove erroneous scenario column from degree days mmm summary CSVs

- routes/__init__.py
This is a simple PR for forcing all of the routes to redirect to '/' when the SITE_OFFLINE environment variable is set to True. 
To test this:
- Verify that the site works as expected when the SITE_OFFLINE variable is unset
- export SITE_OFFLINE=True & verify that the site shows the maintenance notice when going to http://localhost:5000
- Try to go to any of the routes to verify a redirect to the site offline message:
http://localhost:5000/temperature/
http://localhost:5000/indicators/
> Adds a decorator to all routes that redirects to the root of the site ('/') if SITE_OFFLINE is True.

- routes/taspr.py
This PR expands the route definitions for temperature, precipitation, and taspr to no longer have a wildcard "catch all" start to the endpoint. Without this change, any non-existent endpoint that ends in point/<lat>/<lon> or area/<areaID> was resolving to these endpoints and causing an uncaught error to appear in Varnish (HTTP 503 error).
Example failure:
https://earthmaps.io/foo/bar/point/65/-156
If you run this code, and attempt that endpoint, it correctly gives a "bad request" error message:
http://localhost:5000/foo/bar/point/65/-156
Ensure that you can still get access to the temperature, precipitation, and taspr endpoints for both lat / lon and area summaries.
http://localhost:5000/temperature/point/65.0628/-146.1627
http://localhost:5000/precipitation/point/65.0628/-146.1627 …
> Modifies temperature, precipitation, and taspr routes to not use a wildcard for the endpoint.

- luts.py
- routes/fire.py
- templates/documentation/fire.html
This PR adds the AQI and PM2.5 concentration forecasts to the /wildfire/point endpoint. This is used by the Alaska Wildfire Explorer to show the values for a given point that is selected either via community name or lat / lng.
Example: http://localhost:5000/fire/point/65.0628/-146.1627
> Adds AQI and PM2.5 concentration forecasts to the /fire endpoint

- csv_functions.py
- luts.py
- postprocessing.py
- routes/__init__.py
- routes/demographics.py
- templates/documentation/demographics.html
- templates/index.html
This PR adds an endpoint for the demographics data associated with the EPA-Justice project. The data is accessed via WFS request to the `demographics:demographics` layer on GeoServer, and the response is reformatted for output as JSON or CSV.
The dataset is organized by community, and so the endpoint uses the community IDs found at [earthmaps.io/places/communities](https://earthmaps.io/places/communities). For example, data for Anchorage (`AK15`) is found at the endpoint below:
[http://127.0.0.1:5000/demographics/AK15](http://127.0.0.1:5000/demographics/AK15)
Every request also automatically returns data for the state of Alaska and the United States. I've also added an option to specify `all` in place of a community ID, which will request data for all communities in the dataset.
**TO …
> Demographics

- csv_functions.py
This PR fixes a bug that was causing HTTP 500 errors for all beetle CSV downloads, like this for example:
http://127.0.0.1:5000/beetles/point/64.74/-156.22?format=csv
This is because `csv_functions.py` explicitly returns an HTTP 500 error page when the `endpoint` variable doesn't match any of the known CSV endpoints. When `cmip6_indicators` was added as a CSV endpoint option, it was added using `if` instead of `elif`, which created a new `if`/`elif`/`else` chain that effectively made the script forget about the "beetles" endpoint option.
To test, run the API off this branch and verify that the CSV download link above works & returns a valid beetle CSV.
> Fix beetle CSV HTTP 500 bug

- routes/wet_days_per_year.py
This PR adds the missing checks for returned error tuples in the projected data results and rendering them if there is an issue getting data back from Rasdaman.
This will fix the case where the network cuts out or the Rasdaman server returns any of the error codes we expect to need to render for the /eds/wet_days_per_year/point/
Working endpoint: http://localhost:5000/eds/wet_days_per_year/point/62.15/-155.65
Failing endpoint showing error condition: http://localhost:5000/eds/wet_days_per_year/point/62.15/-115.65
Non-working endpoint on production site: https://earthmaps.io/eds/wet_days_per_year/point/62.15/-115.65
NOTE: The error case in #459 could only occur previous when the data is returned correctly for the historical data and incorrectly for any of the projected data which would be …
> Modifies EDS endpoint for Wet Days Per Year with checks for error conditions being returned

- csv_functions.py
This PR fixes the issue of the filename structure of the download CSVs from the API on different browsers. For example, in Firefox, we were getting: _Precipitation for Utqiaġvik (Barrow).csv_ while in Sarari, we were seeing the HTML entities showing up in the filename like this: Precipitation for Utqia%C4%A1vik%20%28Barrow%29.csv
I modified the code to remove the unneeded double quotes in the response header's representation of the filename, and that fixed the issue per this Stack Overflow article: [CSV Underscore Issue](https://stackoverflow.com/questions/22477273/firefox-and-chrome-appending-underscore-before-and-after-file-name-while-interne)
Additionally, I found that if I remove the second properties["filename"] in this code: …
> Fixes CSV download filenames for all modern browsers

- csv_functions.py
This PR removes the three lines of code that added the Obu and Jorg fields to the returned CSVs for the permafrost endpoint that are no longer referenced in the header information of the CSV.
An example endpoint: http://localhost:5000/permafrost/point/65.0628/-146.56?format=csv
Closes #438 
Closes #332
> Removes the Obu and Jorg fields from the returned permafrost CSVs

- templates/documentation/indicators.html
This PR Is a simple documentation fix that matches the documentation anchor link placement for other sections of the API.
Closes #422
> NCAR documentation reference fix

- csv_functions.py
- fetch_data.py
- postprocessing.py
- routes/__init__.py
- routes/cmip6.py
This PR implements a new CMIP6 endpoint that serves the following variables at monthly temporal resolution:
- clt
- evspsbl
- hfls
- hfss
- pr
- pls
- rlds
- rsds
- sfcWind
- tas
- tasmax
- tasmin
- ts
- uas
- vas
The variables are pulled from the `cmip6_monthly` coverage on Apollo. The variables are stored in their own coverage axis and the new API endpoint uses axis subsetting to pull only the variables that are requested to improve performance. CSV export support is also implemented.
To test, run the API like this:
```
git checkout cmip6_monthly
export FLASK_APP=application.py
export API_RAS_BASE_URL=https://apollo.snap.uaf.edu/rasdaman/
```
Then, you can fetch the full set of variables all at once like this (this may take a couple minutes): …
> Add new monthly CMIP6 endpoint

- generate_urls.py
- routes/fire.py
- templates/documentation/fire.html
This PR adds the WFS search query that finds all fires within ~70 miles of the selected point and returns the points and polygons inside of two additional JSON keys: fire_points and fire_polygons. To test, try points around the state of Alaska to see the returned data and ensure that the documentation for this returned data is clear. 
This also removes an unused endpoint /wildfire that has no purpose remaining available.
Closes #424 
Closes #446
> Adds the WFS query for generating nearby fires to the /fire endpoint

- routes/alfresco.py
Closes #135 
This is a similar problem to the one fixed in PR #464 , and I just copied the solution from there.
To test:
Fire up the API and make sure these endpoints render a template instead of a tuple error:
http://localhost:5000/alfresco/flammability/local/52.938/-168.868
http://localhost:5000/alfresco/flammability/local/53.267/-168.217
> Fixes tuple return error in ALFRESCO endpoint

- csv_functions.py
- routes/degree_days.py
- routes/permafrost.py
- routes/taspr.py
- routes/wet_days_per_year.py
This PR adds the date range selected from any endpoint that has a start year & end year and puts it into both the metadata and the file name of the CSV files. This works for all of the Degree Day 
Examples:
**Temperature**
- http://localhost:5000/temperature/65.0628/-146.1627/1940/2060?format=csv
**Temperature in January**
- http://localhost:5000/temperature/jan/65.0628/-146.1627/1940/1970?format=csv
**Precipitation**
- http://localhost:5000/precipitation/65.0628/-146.1627/1980/2080?format=csv
**Degree Days** 
- http://localhost:5000/degree_days/freezing_index/65.0628/-146.1627/1990/2080?format=csv
- http://localhost:5000/degree_days/heating/65.0628/-146.1627/1970/2050?format=csv
**Wet Days per Year**
- http://localhost:5000/wet_days_per_year/projected/point/65.0628/-146.1627/2020/2080?for …
> Adds the range of years to the CSVs that are generated for any endpoints with start and end years

- application.py
- csv_functions.py
- fetch_data.py
- generate_urls.py
- routes/alfresco.py
- routes/beetles.py
- routes/eds.py
- routes/elevation.py
- routes/fire.py
- routes/hydrology.py
- routes/indicators.py
- routes/permafrost.py
- routes/physiography.py
- routes/taspr.py
- routes/wet_days_per_year.py
- validate_data.py
- validate_request.py
This PR replaces all of the unnecessary star imports in the API and explicitly calls the functions that it needs to operate in each route and functionality. 
To test, ensure that all of the endpoints are still operational after this change as this touches a number of different routes and files that contain functions used across the API. 
Closes #349 
Closes #401
> Replaces all unnecessary star imports for functions across the API and changes fetch_data_api function name

- application.py
Closes #484.
This PR simply adds `import re` back into `application.py` to fix our regex GET parameter validation.
To replicate the problem:
```
git checkout main
export FLASK_APP=application.py
```
And observe the error when using the `vars` GET parameter here:
http://localhost:5000/cmip6/point/65/-147?vars=tas,sfcWind
To see the fix:
```
git checkout import_re_module
```
And visit this same URL (you may need to do a hard reload with Shift + Reload to see the difference):
http://localhost:5000/cmip6/point/65/-147?vars=tas,sfcWind
> Restore "import re" to fix GET parameter validation

- templates/index.html
This fixes a grammatical error identified by Charlie regarding our data endpoints on our index page. 
Closes #483
> Updates grammatical error in our index page.

- fetch_data.py
- luts.py
- routes/vectordata.py
- validate_data.py
- validate_request.py
This PR incorporates the following new Yukon areas into the API:
- Yukon Fire Districts (YTFD*)
- Yukon Game Management Subzones (YTGMA*)
- Yukon Watersheds (YTHYDRO*)
The code in this PR is currently using the `playground:all_areas_test5` layer/shapefile from GeoServer, which is the soon-to-be production layer/shapefile that includes all previous polygons + the new Yukon areas listed above. **This is to help us with testing, but we'll need to change this back to `all_boundaries:all_areas` before merging this branch into `main`, and also update that layer in GeoServer.** Once this PR is marked as approved, I'll do this cleanup work before merging.
To test:
- Boot up the API from this branch, pointed at Apollo (default)
- Go to http://localhost:5000/places/all and confirm that each of the …
> Incorporate more types of Yukon areas

- csv_functions.py
- fetch_data.py
- generate_requests.py
- generate_urls.py
- postprocessing.py
- routes/landfastice.py
- templates/422/invalid_latlon_outside_coverage.html
- templates/documentation/landfastice.html
- validate_request.py
This PR basically swaps the backend for the landfast sea ice endpoint. The endpoint is functionally quite similar, but the geographic and temporal ranges are extended. The possible set of returned values is also a bit different. Check the refreshed template for details. Here's what to look for in this review (some of this was foreshadowed in our tech gardening / show+tell chat):
* Checkout the new function `generate_wcps_describe_coverage_str` in the `generate_requests` module. We're forming a request to describe the coverage using the WCPS `describe()` operator because we can get a response that is a well-formatted JSON that is far easier to parse than the prior XML/string babble. We'll see how this is used later on.
* Next, look at the new `generate_describe_coverage_url` function in …
> Landfastice update

- fetch_data.py
- postprocessing.py
- routes/alfresco.py
- routes/cmip6.py
- routes/degree_days.py
- routes/hydrology.py
- routes/indicators.py
- routes/permafrost.py
- routes/snow.py
- routes/wet_days_per_year.py
- validate_request.py
This PR replaces usage of `fetch_data.get_dim_encodings()` with `fetch_data.describe_via_wcps()` across all routes where the former function was used. We are making this PR because something broke between Rasdaman versions, and the prior method of getting the necessary OGC coverage dimensional encodings was failing.
- Created new `get_coverage_encodings()` function in the `validate_request.py` module
- Refactored 8 routes to use the new pattern:
- `alfresco.py`
- `degree_days.py` 
- `snow.py`
- `cmip6.py`
- `hydrology.py`
- `indicators.py`
- `permafrost.py`
- `wet_days_per_year.py`
- Moved endpoint-specific configurations (like EDS era mappings) to separate configs
- Fixed time index generation in permafrost route to use actual metadata
- Verified `get_dim_encodings()`, `get_xml_content` …
> Refactor dim encodings fetch

- routes/vectordata.py
This PR updates the community endpoints to include these new fields in their responses:
- `is_coastal`
- `ocean_lati`
- `ocean_long`
It works with the following endpoints:
http://localhost:5000/places/all
http://localhost:5000/places/communities
http://localhost:5000/places/search/71.1/-156.3
These fields currently are **not** included in CSV exports, however:
http://localhost:5000/places/communities?format=csv
The field name truncation is a little rough, but I figure it's better to fix this upstream (https://github.com/ua-snap/geospatial-vector-veracity/issues/135) rather than clean up the names in the API code.
To run:
```
export FLASK_APP=application.py
export API_GS_BASE_URL=https://gs.earthmaps.io/geoserver/
```
> Include is_coastal, ocean_lati, and ocean_long fields in community responses

- application.py
- config.py
- routes/cmip6.py
- templates/422/invalid_latlon_outside_coverage.html
- templates/documentation/cmip6.html
- validate_request.py
This PR is a first shot at the monthly CMIP6 endpoint, which fetches data from the `cmip6_monthly_cryo_test` coverage which currently includes the complete set of "V1" variables. There are a few known issues with this endpoint (listed below) but this should make for a decent start.
Fire up the API, being sure to set your environment like so:
```
export API_GS_BASE_URL=http://earthmaps.io/geoserver/
export API_RAS_BASE_URL=https://zeus.snap.uaf.edu/rasdaman/
```
1. Check out the documentation page at `http://127.0.0.1:5000/cmip6/`. 
**Known issues**: lacks sources/citations. Variable definitions are a bit clunky and may require some reformatting.
2. Test some requests, make sure all the options work, try to break it. This is a pan-Arctic coverage, so anything north of 50 degrees latitude …
> Add CMIP6 endpoint, using "cryo" coverage

- routes/indicators.py
This PR makes a small modification to the CMIP6 Indicators route such that it fetches the spatial bounds from rasdaman and constructs a bounding box to validate the lat-lon of the request.
This should enable locations to have both their CMIP6 data and CMIP6 indicators queried.
To test this PR, make sure you are pointing at datacubes and then try routes like this:
You should get data here:
http://localhost:5000/indicators/cmip6/point/50.5/-147
But not here:
http://localhost:5000/indicators/cmip6/point/49.5/-147
For the latter, the map isn't great but IMO that is OK for now. Also, the bounding box reported on this page **is accurate** due to the weirdness of the re-grid. However, any requests for latitude 90.1 or something will get caught by this block:
```python
validation = …
```
> Fix cmip6 indicators bbox validation

- routes/vectordata.py
This PR is a tiny change that simply updates these `all_communities` field names from their old truncated names:
- `ocean_lati`
- `ocean_long`
To their new, non-truncated names:
- `ocean_lat1`
- `ocean_lon1`
The shapefile has already been updated on gs.earthmaps.io, so the the API needs this fix ASAP to continue working as expected. This is a trivial change, so I'm going to self-merge this.
> Update community nearest ocean lat/lon field names

- static/style.css
- templates/base.html
- templates/documentation/cmip6.html
closes #514 
This PR completes basic documentation for the CMIP6 endpoint with V1 variables. Source citation is TBD and will be returned to after consultation with Jeremy Litell.
To test: 
Start up the API, being sure to set environmental variables like so:
```
export API_GS_BASE_URL=http://earthmaps.io/geoserver/
export API_RAS_BASE_URL=https://zeus.snap.uaf.edu/rasdaman/
```
Review the documentation at `http://localhost:5000/cmip6/`
> CMIP6 endpoint documentation

- templates/base.html
This PR forces the Data API's HTML pages to use light mode. I double checked that there's only one `<body>` tag throughout the entire webapp, and added the `data-theme="light"` attribute to it to force Bulma to use light mode.
I tried going the CSS route before this and it turned into a very long series of manual CSS rule tweaks for each title, subtitle, heading, quotation block, etc. So this is definitely the more bulletproof and cleaner solution.
This fix works for me in Chrome, Firefox, and Safari.
> Disable Bulma dark mode

- routes/permafrost.py
This PR fixes the permafrost returns when there is no data available. The previous endpoints were hitting 500 errors due to the values of the returned data being shown as strings rather than a dictionary for pulling out the values from the keys.
An example of this can be seen on the current main branch:
[http://localhost:5000/eds/permafrost/59.8164/-151.0895](http://localhost:5000/eds/permafrost/59.8164/-151.0895)
[2025-02-03 09:19:35,036] ERROR in app: Exception on /eds/permafrost/59.8164/-151.0895 [GET]
Traceback (most recent call last):
File "/Users/rltorgerson/.local/share/virtualenvs/cw-5qLQ3xep/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
> Fixes issues with permafrost when no data exists

- config.py
- routes/beetles.py
- routes/permafrost.py
This PR fixes the slowdowns seen by the cache returns for coastal and Canadian communities in the NCR for both the permafrost and beetle API endpoints. 
In both cases, we were returning 500 errors that get translated as 503s from the cache, and these 500 errors were not being cached, thus causing a constant need to retry those endpoints on each request. They both had logic errors that required a small fix to allow for them to return 404 errors which is really what these endpoints are supposed to return for these locations. 
Closes #533
> Fixes errors with permafrost and beetles coverages near coastal and Canadian communities

- csv_functions.py
- templates/documentation/indicators.html
Closes #527.
Closes #531.
This PR:
- Adds missing units for the `cd`, `hd`, `rx1day`, and `rx5day` NCAR indicators on the http://127.0.0.1:5000/indicators/ documentation page.
- Adds missing units for `cd` and `hd` in NCAR indicators CSV metadata. For example: http://127.0.0.1:5000/indicators/base/point/61.5/-147?format=csv
To test:
```
export FLASK_APP=application.py 
```
No other environment variables are necessary.
> Add missing units for the "cd", "hd", "rx1day", and "rx5day" indicators

- templates/422/invalid_latlon.html
- templates/422/invalid_latlon_outside_coverage.html
- templates/documentation/elevation.html
- templates/documentation/indicators.html
- templates/documentation/seaice.html
Closes #539.
I did some research and it sounds like the dark mode issue relating to the `<strong>` element is an issue/bug with Bulma itself. But because Bulma provides a `has-text-weight-bold` text-weight typography helper, it's easy to get around this by replacing instances of `<strong>` with `<span class="has-text-weight-bold">`, so that's what this PR does on the following pages:
http://127.0.0.1:5000/indicators/
http://127.0.0.1:5000/seaice/
I also discovered that two of our error templates had the same problem and fixed those as well:
http://127.0.0.1:5000/degree_days/heating/45.0628/-136.1627 (invalid lat/lon error page)
http://127.0.0.1:5000/landfastice/point/50.6123/-139.8869 (outside of coverage error page)
I also went ahead and removed the `<strong>` element from the Elevation …
> Replace all instances of <strong> to fix dark mode issues

- routes/cmip6.py
- templates/documentation/cmip6.html
- templates/documentation/cmip6_refs.html
This PR adds a standalone CMIP6 reference page linked from CMIP6 documentation. 
To test, start the API as usual and review the CMIP6 documentation. Click some of the DOI links to make sure they point to the right dataset, and that the author information is correct.
Closes #444
> Add CMIP6 reference page

- routes/indicators.py
- templates/documentation/indicators.html
This PR adds an alternate "cmip5" route to the indicators endpoint, and includes this route in the API documentation for consistency with the new "cmip6" indicators route.
The old "base" route is left intact, so that no apps break. 
To test, start the API as usual and review the climate indicators documentation. Test some links using the new "cmip5" option, e.g. http://localhost:5000/indicators/cmip5/area/1903040601
closes #515
> Use "cmip5" in addition to "base" for indicators

- validate_request.py
This PR modifies the location in which the code looks for the metadata section "Encoding" when starting up the API. Previously, we had all of our Encoding metadata in the "local" section of the ingests which resulted in redundant copies of that metadata for each slice of the coverage, which could actually slow down response times on given coverages with numerous (thousands) slices. 
To test this change, make sure that you can still start up the API when pointed at Apollo or Zeus. Apollo is currently the server that has the coverages ingested with the global section containing the Encoding string, which is what required this change in the first place.
Testing:
export API_RAS_BASE_URL=https://zeus.snap.uaf.edu/rasdaman/
Expected: API starts up normally and the endpoints …
> Updates where the code should look for the Encoding string in the coverage metadata in Rasdaman.

- routes/cmip6.py
- validate_request.py
This PR makes the changes necessary to fetch data from the `cmip6_monthly` coverage on Apollo, which now has E3SM model data included. 
This coverage differs from the production `cmip6_monthly` on Zeus in that it has an encoding dictionary with integer keys rather than string keys. Previously, we had to convert the keys to strings in order to fetch values from the encodings dictionary, but this branch removes that temporary patch. 
For this reason, even though the `validate_request.get_coverage_encodings()` function has been changed to find the encodings dictionary in both production and development coverage metadata (which ensures the app will start no matter which Rasdaman server its pointed at), the actual data fetching from production `cmip6_monthly` coverage will fail if this is …
> test cmip6_monthly_e3sm coverage

- routes/indicators.py
Closes #569.
Somewhere along the way, both the CMIP6 indicators and CMIP5 indicators point query endpoints stopped working, producing server errors. Looks like this was just a case of the corresponding Rasdaman coverage string variables not getting updated during a code refactor, or maybe an automerge glitch. This PR fixes this.
After fixing this, I also noticed that the CMIP6 `rx1day` indicator values were not rounded. All values had ~13 decimal points, like `14.3096173647791`. I went ahead and rounded these values to the nearest whole number, since that's how we generally display values that are in millimeters.
To test, make sure each of these two endpoints are working and the `rx1day` values in the CMIP6 indicator endpoint have a sane level of precision: …
> Fix indicator point queries

- routes/temperature_anomalies.py
This PR is a small fix to the Temperature Anomalies endpoint that is necessary for Zeus compatibility. On Apollo, NoData values from the Temperature Anomalies coverages are returned from WCS as `-9999`. On Zeus, the same values are returned as a `null`. This change makes sure that a value is not `None` (converted from JSON `null`) before attempting to round it.
To test, run the Data API against Zeus:
```
export FLASK_APP=application.py
export API_RAS_BASE_URL=https://zeus.snap.uaf.edu/rasdaman/
```
Then verify that a Temperature Anomalies URL like this returns data, not a server error:
http://127.0.0.1:5000/temperature_anomalies/point/63.73/-166.32
> Add extra Temperature Anomaly value check for Zeus compatibility

- csv_functions.py
This is a small change to the formatting of the demographics CSV. The CSV should now show the community (or communities) as the first column, followed by Alaska and US.
To test, point the API at Apollo and at the dev GS:
```
export API_RAS_BASE_URL=https://apollo.snap.uaf.edu/rasdaman/
export API_GS_BASE_URL=https://gs-dev.earthmaps.io/geoserver/
```
and request a demographics CSV (e.g., http://127.0.0.1:5000/demographics/AK15?format=csv )
The community should be the first column of data, followed by Alaska and US.
> Demographics CSV order

- templates/documentation/demographics.html
closes #552 
Note that the source data link still points to the SDOH homepage. This is because the "Non-Medical Factor Measures" does not have a homepage. Basically, the dataset name changed in the CDC API and online data explorer, but the over-arching project name still seems to be SDOH.
Clear as mud :)
> update dataset name and access date

- Procfile
- routes/eds.py
This PR is a refactoring of the ArcticEDS endpoint /eds/all/ which now will make requests directly to the functions contained within the routes rather than using asyncio to call the endpoints at the URL of the API. This was done because the ArcticEDS functionality was broken in the new API on Elastic Beanstalk and would never return any values, instead timing out after waiting for a response that would never return. 
The data returned between the main branch and this branch should be identical as they are calling the same functions with the same input data, so try a few locations between the main branch and the refactor_eds branch. 
Note: The /eds/all endpoint still takes a very long time to complete (3-5 minutes), so get yourself a drink while you wait for the end results.
> Refactor the ArcticEDS endpoint for use in Elastic Beanstalk

- routes/eds.py
This PR refactors the `/eds/all` endpoint to return the HTTP 500 error code/template if any of its child endpoints returns an HTTP 500 response. HTTP 404s, etc., are still treated as null/nodata responses as before, and as intended.
To test this, I ran the Data API locally (pointed at Zeus + gs-dev.earthmaps.io), and then ran this throwaway Python script in a different terminal window to verify that HTTP 500 status codes were occasionally returned from the `/eds/all` endpoint:
```python
#!/usr/bin/env python3
import requests
import random
from time import sleep
while True:
lat = round(random.uniform(60, 70), 2)
lon = round(random.uniform(-160, -140), 2)
url = f"http://127.0.0.1:5000/eds/all/{lat}/{lon}"
response = requests.get(url)
print(f"{url}: {response.status_code}")
sleep(3)
```
I …
> Propagate HTTP 500 errors from child EDS endpoints to /eds/all parent endpoint

- csv_functions.py
Closes #639.
This PR simply fixes a typo. Self-merging because this is a trivial change.
> Fix "minimum" typo in CMIP6 monthly CSV metadata
